sidebar
Austral1a/project pull request #1
Opened 2020-12-07 13:32 UTC by Austral1a

2020-12-08 13:43 UTC, MagroTanya requested changes

2020-12-08 13:49 UTC, Austral1a commented on src/Components/Sidebar/Sidebar.module.scss
> +  min-width: 150px;
I have deleted width from .sidebar at all, it doesn't need there.

2020-12-09 07:37 UTC, MagroTanya requested changes

2020-12-09 07:37 UTC, MagroTanya commented on src/сomponents/Sidebar/Sidebar.module.scss
> +    @include wh100ViewPort;
it's better to call this mixin **fullScreen**

2020-12-09 07:37 UTC, MagroTanya commented on src/сomponents/Sidebar/Sidebar.module.scss
> +  width: 55px;
use BEM, _closed_ is **modifier** and should be --closed. And use & to build class names

2020-12-09 07:37 UTC, MagroTanya commented on src/сomponents/Sidebar/Sidebar.module.scss
> +    -webkit-box-shadow: none;
use & to build class names

2020-12-09 07:37 UTC, MagroTanya commented on src/сomponents/Sidebar/Sidebar.tsx
> +  item1: {
We spoke about array of objects. Please change it

2020-12-09 07:37 UTC, MagroTanya commented on src/сomponents/Sidebar/Sidebar.tsx
> +            className={classes["sidebar__background"]}
background isn't **element**, should be **sidebar-background**

2020-12-09 07:37 UTC, MagroTanya commented on src/сomponents/Sidebar/components/SidebarItem/SidebarItem.tsx
> +      className={classes["sidebar-content__item"]}
the same **selected** is **modifier**

2020-12-09 07:44 UTC, Austral1a commented on src/сomponents/Sidebar/Sidebar.module.scss
> +    -webkit-box-shadow: none;
I cannot use "&" here, cause the parent class of ".sidebar-overlay" and ".sidebar-content" is ".sidebar_close" rather than ".sidebar".

2020-12-09 10:48 UTC, MagroTanya requested changes

2020-12-09 10:48 UTC, MagroTanya commented on src/Main.tsx
> +  const {
move hook to sidebar component

2020-12-09 10:54 UTC, merged